### ISSUE TITLE
タスクリスト

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_mobile#28]
- [x] Voicevox Coreと周辺ライブラリのiOS/Androidビルド
  - [x] Android/arm64（実機）https://github.com/VOICEVOX/voicevox_core/pull/444
  - [x] Android/x86_64（エミュ）
    - [x] https://github.com/VOICEVOX/onnxruntime-rs/pull/21
    - [x] https://github.com/VOICEVOX/open_jtalk-rs/pull/13
    - [x] VOICEVOX/voicevox_core#473
  - [x] iOS（実機）VOICEVOX/voicevox_core/pull/471
- [x] voicevox/voicevox_mobile#1
- [ ] エディタのUIをスマホフレンドリー化
  - [ ] https://github.com/VOICEVOX/voicevox_mobile/pull/27 で追加された、MobileHeaderBarを良い感じにPC版と統合する
- [x] voicevox/voicevox_core#479
  - [ ] voicevox/voicevox_core#370 の追従
- [ ] （オプション）voicevox/voicevox_core#265
- [ ] コアFFIベースのエンジン作成
  - [ ] Capacitorプラグインの作成
    - [x] Android
    - [ ] iOS
  - [x] OpenAPIのコネクター風に触れるオブジェクトの作成

_オリジナルは @sevenc-nanashi が https://github.com/VOICEVOX/voicevox_project/issues/10#issuecomment-1517028592 にポスト_

（GitHub Mobileに転送機能なんてあったんだ）
